### ISSUE TITLE
issue when installing

### ISSUE THREAD

**Issue by nyxical420** [jnsougata/discohook#48]
pip error log:
```
Collecting git+https://github.com/jnsougata/discohook
  Cloning https://github.com/jnsougata/discohook to c:\users\nyxical\appdata\local\temp\pip-req-build-zg3l20ui
  Running command git clone --filter=blob:none --quiet https://github.com/jnsougata/discohook 'C:\Users\nyxical\AppData\Local\Temp\pip-req-build-zg3l20ui'      
  Resolved https://github.com/jnsougata/discohook to commit c71483aeb472af51f54de79a930ff2e331da2b03
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp (from discohook==0.0.6a518+gc71483a)
  Using cached aiohttp-3.9.1-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Collecting ed25519 (from discohook==0.0.6a518+gc71483a)
  Using cached ed25519-1.5.tar.gz (868 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      C:\Users\nyxical\AppData\Local\Temp\pip-install-0rkcke9p\ed25519_87d27c588b44494a9af0a2445a666e2b\versioneer.py:467: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "C:\Users\nyxical\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\nyxical\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\nyxical\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\nyxical\AppData\Local\Temp\pip-build-env-_01pxbv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\nyxical\AppData\Local\Temp\pip-build-env-_01pxbv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires  
          self.run_setup()
        File "C:\Users\nyxical\AppData\Local\Temp\pip-build-env-_01pxbv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\nyxical\AppData\Local\Temp\pip-build-env-_01pxbv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 115, in <module>
        File "C:\Users\nyxical\AppData\Local\Temp\pip-install-0rkcke9p\ed25519_87d27c588b44494a9af0a2445a666e2b\versioneer.py", line 1405, in get_version       
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\nyxical\AppData\Local\Temp\pip-install-0rkcke9p\ed25519_87d27c588b44494a9af0a2445a666e2b\versioneer.py", line 1339, in get_versions      
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\nyxical\AppData\Local\Temp\pip-install-0rkcke9p\ed25519_87d27c588b44494a9af0a2445a666e2b\versioneer.py", line 399, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with 
pip.
```

python version: Python 3.12.0

**Comment by jnsougata** [comment]
I guess you have to install `python3-pip` to your system

**Comment by LyubomirT** [comment]
> I guess you have to install `python3-pip` to your system

First of all, it seems like the user has a Windows system and `pip` is either installed along with Python 3 (via .exe) or using the command line (after Pytnon is installed). Second, the error shows that something went wrong while building the wheel for your project and it most likely is *not* a problem with pip. I'm not sure what causes this, but it clearly is not with the setup of @nyxical420.

**Comment by jnsougata** [comment]
It was most likely an issue from the library `ed25519` which have been replaced with `pynacl` recently.

**Comment by LyubomirT** [comment]
In that case, Discohook probably should switch to Pynacle?

**Comment by jnsougata** [comment]
Already switched. Thanks.
